In [ ]:
import shutil
shutil.unpack_archive('aclImdb_v1.tar.gz', 'movie')

In [2]:
import os
root = 'movie/aclImdb'
list_test_file_pos = os.listdir(os.path.join(root, 'test/pos'))
list_test_file_neg = os.listdir(os.path.join(root, 'test/neg'))

In [ ]:
from sklearn.model_selection import train_test_split
list_val_file_pos, list_test_file_pos = train_test_split(list_test_file_pos, test_size=0.4, random_state=42)
list_val_file_neg, list_test_file_neg = train_test_split(list_test_file_neg, test_size=0.4, random_state=42)
len(list_val_file_pos)

In [ ]:
os.mkdir(os.path.join(root, 'val'))
os.mkdir(os.path.join(root, 'val/pos'))
os.mkdir(os.path.join(root, 'val/neg'))

In [ ]:
test_pos_path = os.path.join(root, 'test/pos')
val_pos_path = os.path.join(root, 'val/pos')
test_neg_path = os.path.join(root, 'test/neg')
val_neg_path = os.path.join(root, 'val/neg')

for file in list_val_file_pos:
    shutil.move(os.path.join(test_pos_path, file), os.path.join(val_pos_path, file))
    
for file in list_val_file_neg:
    shutil.move(os.path.join(test_neg_path, file), os.path.join(val_neg_path, file))

In [1]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
from collections import Counter
def get_vocal(dataset):
    c = Counter()
    for data in dataset:
        c.update(tf.strings.split(data).numpy())
    return list(c.keys())


In [ ]:
str(t.numpy()).split(' ')

In [10]:
def preprocess(pos_path, neg_path, n_batch=32, n_shuffle_buffer=0, n_read_threads=5):
    p_dataset = tf.data.Dataset.list_files([os.path.join(pos_path, file) for file in os.listdir(pos_path)])
    p_dataset = dataset.interleave(lambda file: tf.data.TextLineDataset(file), cycle_length=5, num_parallel_calls=n_read_threads)
    p_dataset = dataset.map(lambda X: (X, 0), num_parallel_calls=n_read_threads)
    n_dataset = tf.data.Dataset.list_files([os.path.join(neg_path, file) for file in os.listdir(neg_path)])
    n_dataset = dataset.interleave(lambda file: tf.data.TextLineDataset(file), cycle_length=5, num_parallel_calls=n_read_threads)
    n_dataset = dataset.map(lambda X: (X, 1), num_parallel_calls=n_read_threads)
    dataset = tf.data.Dataset.concatenate(p_dataset, n_dataset).repeat(n_shuffle_buffer)
    return dataset.batch(n_batch).prefetch(1)

In [ ]:
test_pos_path = os.path.join(root, 'test/pos')
val_pos_path = os.path.join(root, 'val/pos')
test_neg_path = os.path.join(root, 'test/neg')
val_neg_path = os.path.join(root, 'val/neg')
train_pos_path = os.path.join(root, 'train/pos')
train_neg_path = os.path.join(root, 'val/neg')

n_batch = 32
n_shuffer_buffer = 25000 
train_set = preprocess(train_pos_path, train_neg_path, n_batch, n_shuffer_buffer)
test_set = preprocess(test_pos_path, test_neg_path, n_batch)
val_set = preprocess(val_pos_path, val_neg_path, n_batch)

['movie/aclImdb/val/pos/1930_9.txt',
 'movie/aclImdb/val/pos/3205_9.txt',
 'movie/aclImdb/val/pos/147_10.txt',
 'movie/aclImdb/val/pos/7511_7.txt',
 'movie/aclImdb/val/pos/616_10.txt',
 'movie/aclImdb/val/pos/10460_10.txt',
 'movie/aclImdb/val/pos/1975_9.txt',
 'movie/aclImdb/val/pos/4381_9.txt',
 'movie/aclImdb/val/pos/4667_7.txt',
 'movie/aclImdb/val/pos/6983_7.txt',
 'movie/aclImdb/val/pos/7463_9.txt',
 'movie/aclImdb/val/pos/2612_10.txt',
 'movie/aclImdb/val/pos/1807_7.txt',
 'movie/aclImdb/val/pos/3474_10.txt',
 'movie/aclImdb/val/pos/2384_8.txt',
 'movie/aclImdb/val/pos/803_10.txt',
 'movie/aclImdb/val/pos/12363_7.txt',
 'movie/aclImdb/val/pos/5775_10.txt',
 'movie/aclImdb/val/pos/10813_7.txt',
 'movie/aclImdb/val/pos/10167_9.txt',
 'movie/aclImdb/val/pos/5124_10.txt',
 'movie/aclImdb/val/pos/4038_9.txt',
 'movie/aclImdb/val/pos/9919_9.txt',
 'movie/aclImdb/val/pos/7422_10.txt',
 'movie/aclImdb/val/pos/4669_8.txt',
 'movie/aclImdb/val/pos/3590_9.txt',
 'movie/aclImdb/val/pos/4451

In [56]:
t = tf.constant(['ds aa', 'd asa t', 't r g'])

In [71]:
data = tf.data.Dataset.from_tensor_slices(t)
data

<TensorSliceDataset shapes: (), types: tf.string>

In [58]:
from collections import Counter
data = data.map(lambda d : tf.strings.split(d))
c = Counter()
for d in data:
    print(list(d.numpy()))
    c.update(list(d.numpy()))
c.keys()


[b'ds', b'aa']
[b'd', b'asa', b't']
[b't', b'r', b'g']


dict_keys([b'ds', b'aa', b'd', b'asa', b't', b'r', b'g'])

In [42]:
import numpy as np

In [43]:
a = np.array([1,2,4,4])

In [59]:
c.values()

dict_values([1, 1, 1, 1, 2, 1, 1])

In [61]:
for d in tf.constant(['dasd', 'das']):
    print(d)

tf.Tensor(b'dasd', shape=(), dtype=string)
tf.Tensor(b'das', shape=(), dtype=string)


In [63]:
tf.constant(1) + 1

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [65]:
a = tf.constant(2)

In [73]:
data.to_tensor()

AttributeError: 'TensorSliceDataset' object has no attribute 'to_tensor'

In [160]:
data = tf.constant(['da sda', 'dsa das das', 'ghf gahj fag'])

In [74]:
tf.strings.encode(tf.constant('dasdasasdasd'), 'UTF-8')

AttributeError: module 'tensorflow._api.v2.strings' has no attribute 'encode'

In [161]:
data = tf.strings.split(data)

In [81]:
tf.zeros((2, 3), dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [120]:
for d in data[0]:
    c = Counter(d)

In [121]:
c.keys()

dict_keys([b'ghf', b'gahj', b'fag'])

In [104]:
data.shape

AttributeError: 'list' object has no attribute 'shape'

In [127]:
len(data)

3

In [143]:
d = tf.constant(1)

In [154]:
data = data.numpy

In [155]:
for d in data:
    print(d)

TypeError: 'method' object is not iterable

In [157]:
e = tf.Variable(tf.constant(1))

In [159]:
e.shape

TensorShape([])

In [166]:
len(data[0])

2

In [168]:
a = tf.zeros((2,3))

In [173]:
a[0,0] += 1

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [176]:
initializer = tf.keras.initializers.Zeros()
val = initializer(shape=(2, 2))

In [192]:
data = tf.Variable(tf.zeros((2,3), dtype=tf.int64))

In [189]:
data[tf.constant(0), tf.constant(0)].assign_add(1)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign_add'

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'